language: scala

## Caching seems to cause problems of its own, so we leave it commented for now.
## We use travis_wait instead (see below in the script: section) to give the build more time.
#cache:
#  directories:
#  - $HOME/.ivy2
#  - $HOME/.sbt

#before_cache:
#  - rm -f $HOME/.ivy2/.*.lock $HOME/.ivy2/*.lock

jdk:
  - openjdk8

scala:
  - 2.12.8

script:
  - travis_wait sbt ++$TRAVIS_SCALA_VERSION update
  - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
  - sbt ++$TRAVIS_SCALA_VERSION -Djava.awt.headless=true compile test

